# This workflow will build custom ray image and push to quay.io
name: Build and Push
on:
  push:
    branches:
      - 'workflow'
    # paths:
    #   - images/runtime/examples/ray-torch-cuda/Dockerfile
  workflow_dispatch:
    inputs:
      image:
        description: 'Image name, i.e.: v0.0.1'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Permission required to create a release
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Build image
      run: |
        podman build -t ray-torch-cuda -f images/runtime/examples/ray-torch-cuda/Dockerfile
      
    - name: Login to Quay.io
      id: podman-login-quay
      run: |
        podman login --username ${{ secrets.QUAY_ID }} --password ${{ secrets.QUAY_TOKEN }} quay.io

